/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WDrodzeRouteImport } from './routes/w-drodze'
import { Route as OAutorzeRouteImport } from './routes/o-autorze'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WDrodzeSlugRouteImport } from './routes/w-drodze.$slug'

const WDrodzeRoute = WDrodzeRouteImport.update({
  id: '/w-drodze',
  path: '/w-drodze',
  getParentRoute: () => rootRouteImport,
} as any)
const OAutorzeRoute = OAutorzeRouteImport.update({
  id: '/o-autorze',
  path: '/o-autorze',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WDrodzeSlugRoute = WDrodzeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WDrodzeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-autorze': typeof OAutorzeRoute
  '/w-drodze': typeof WDrodzeRouteWithChildren
  '/w-drodze/$slug': typeof WDrodzeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-autorze': typeof OAutorzeRoute
  '/w-drodze': typeof WDrodzeRouteWithChildren
  '/w-drodze/$slug': typeof WDrodzeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontakt': typeof KontaktRoute
  '/o-autorze': typeof OAutorzeRoute
  '/w-drodze': typeof WDrodzeRouteWithChildren
  '/w-drodze/$slug': typeof WDrodzeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontakt' | '/o-autorze' | '/w-drodze' | '/w-drodze/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontakt' | '/o-autorze' | '/w-drodze' | '/w-drodze/$slug'
  id:
    | '__root__'
    | '/'
    | '/kontakt'
    | '/o-autorze'
    | '/w-drodze'
    | '/w-drodze/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktRoute: typeof KontaktRoute
  OAutorzeRoute: typeof OAutorzeRoute
  WDrodzeRoute: typeof WDrodzeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/w-drodze': {
      id: '/w-drodze'
      path: '/w-drodze'
      fullPath: '/w-drodze'
      preLoaderRoute: typeof WDrodzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-autorze': {
      id: '/o-autorze'
      path: '/o-autorze'
      fullPath: '/o-autorze'
      preLoaderRoute: typeof OAutorzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w-drodze/$slug': {
      id: '/w-drodze/$slug'
      path: '/$slug'
      fullPath: '/w-drodze/$slug'
      preLoaderRoute: typeof WDrodzeSlugRouteImport
      parentRoute: typeof WDrodzeRoute
    }
  }
}

interface WDrodzeRouteChildren {
  WDrodzeSlugRoute: typeof WDrodzeSlugRoute
}

const WDrodzeRouteChildren: WDrodzeRouteChildren = {
  WDrodzeSlugRoute: WDrodzeSlugRoute,
}

const WDrodzeRouteWithChildren =
  WDrodzeRoute._addFileChildren(WDrodzeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktRoute: KontaktRoute,
  OAutorzeRoute: OAutorzeRoute,
  WDrodzeRoute: WDrodzeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
