/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OAutorzeRouteImport } from './routes/o-autorze'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as SeriesRouteImport } from './routes/$series'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeriesSlugRouteImport } from './routes/$series.$slug'

const OAutorzeRoute = OAutorzeRouteImport.update({
  id: '/o-autorze',
  path: '/o-autorze',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/$series',
  path: '/$series',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesSlugRoute = SeriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SeriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$series': typeof SeriesRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/o-autorze': typeof OAutorzeRoute
  '/$series/$slug': typeof SeriesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$series': typeof SeriesRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/o-autorze': typeof OAutorzeRoute
  '/$series/$slug': typeof SeriesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$series': typeof SeriesRouteWithChildren
  '/kontakt': typeof KontaktRoute
  '/o-autorze': typeof OAutorzeRoute
  '/$series/$slug': typeof SeriesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$series' | '/kontakt' | '/o-autorze' | '/$series/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$series' | '/kontakt' | '/o-autorze' | '/$series/$slug'
  id:
    | '__root__'
    | '/'
    | '/$series'
    | '/kontakt'
    | '/o-autorze'
    | '/$series/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeriesRoute: typeof SeriesRouteWithChildren
  KontaktRoute: typeof KontaktRoute
  OAutorzeRoute: typeof OAutorzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/o-autorze': {
      id: '/o-autorze'
      path: '/o-autorze'
      fullPath: '/o-autorze'
      preLoaderRoute: typeof OAutorzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$series': {
      id: '/$series'
      path: '/$series'
      fullPath: '/$series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$series/$slug': {
      id: '/$series/$slug'
      path: '/$slug'
      fullPath: '/$series/$slug'
      preLoaderRoute: typeof SeriesSlugRouteImport
      parentRoute: typeof SeriesRoute
    }
  }
}

interface SeriesRouteChildren {
  SeriesSlugRoute: typeof SeriesSlugRoute
}

const SeriesRouteChildren: SeriesRouteChildren = {
  SeriesSlugRoute: SeriesSlugRoute,
}

const SeriesRouteWithChildren =
  SeriesRoute._addFileChildren(SeriesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeriesRoute: SeriesRouteWithChildren,
  KontaktRoute: KontaktRoute,
  OAutorzeRoute: OAutorzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
